# Generated by Django 2.2.4 on 2019-08-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('intoduction', models.CharField(max_length=100)),
                ('party_number', models.IntegerField(default=0)),
            ],
        ),
    ]
